name: beamer_navigation_example
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  beamer:
    git:
      url: https://github.com/slovnicki/beamer.git
      path: package
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  get: ^4.3.8
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
